# Site settings
title: Spotlight Infosec
email: info@spotlight-infosec.com
url: https://spotlight-infosec.com
description: "Spotlight Infosec LLC provides custom Open Source Intelligence (OSINT) and cyber security solutions to enable our customers to achieve their goals."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Spotlight Infosec LLC

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/spotinfosec

# Build settings
markdown: kramdown
permalink: pretty
